### ISSUE TITLE
Chisel/ProjestE conflict (1.8.9)

### ISSUE THREAD

**Issue by Avalonzo** [Chisel-Team/Chisel#105]
Hello just a heads up I Installed ProjectE and I was then unable to load/create worlds seems to be related to Chisel.

Here is the link to the ProjectE Github ticket I have opened - https://github.com/sinkillerj/ProjectE/issues/1150

Also find enclosed my Latest fml log

[latest-fml-log.txt](https://github.com/Chisel-Team/Chisel/files/93616/latest-fml-log.txt)

**Comment by alexbegt** [comment]
Seems ProjectE is using the old chisel API path for the Chisel2Mapper.

**Comment by Avalonzo** [comment]
Thank you for such a fast reply :)

**Comment by tterrag1098** [comment]
To be fair, there hasn't been an official release with the repackaged API yet. However for 1.8 ours is the only API that exists :P

**Comment by hron84** [comment]
Currently it appears the problem is addressed a bit, at least you can enter into the world, but some stuff still require the older api, e.g. the repair pendant, and it generates a runtime NoClassDefFoundError in every tick when the pendant get chance to run. Is there a way to put at least the empty api classes to the package to avoid log spam?

**Comment by tterrag1098** [comment]
Reproduce on 1.9 and will reopen.
