### ISSUE TITLE
(1.9.4) crash with Optifine

### ISSUE THREAD

**Issue by 0Navis0** [Chisel-Team/Chisel#170]
The Chisel creative menu doesn't diplay correctly when Optifine is installed, and then Minecraft crash with this error : http://pastebin.com/6P7bpwUn
In more the log fills it in an alarming rate of errors repeted again and again when both Chisel and Optifine are installed, here is an example of what I get : http://pastebin.com/GZLGXQPB
Sometimes Minecraft crash when I load/create a world with this error : http://pastebin.com/abSaQHnR

**Comment by Drullkus** [comment]
Optifine probably screwed something up and changed something that broke our end. Report it to them.

**Comment by 0Navis0** [comment]
https://github.com/sp614x/optifine/issues/185

**Comment by Drullkus** [comment]
sp614x/optifine#60 looks related.

EDIT: Yeah... Safe to say that switching to Forge's rendering pipeline would be the best move. 💃 

Maybe for once, Optifine won't break Modded rendering. :D

**Comment by sp614x** [comment]
The problem only appears when shaders are active.
It looks like Chisel is using a custom vertex format which is not compatible with the shaders vertex format.
Custom vertex formats are problematic with shaders because they use extended formats with additional fields (normal, midTexCoord, tangent, blockId).
Blocks and items should generally use DefaultVertexFormats.BLOCK and ITEM to avoid conflicts with shaders.

**Comment by sp614x** [comment]
More details from Chisel & Bits: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/29#issuecomment-205707163
