### ISSUE TITLE
[1.10.2] Crash upon placing a cloud block from Chisel onto slimy grass from TiC

### ISSUE THREAD

**Issue by Zaweri** [Chisel-Team/Chisel#186]
http://pastebin.com/GaAFm2HD

The server keeps crashing when the chunk that contains said block is loaded. A player on our server placed a cloud block onto slimy grass, and this occurred. I will report this to the Tinkers' Construct mod authors as well.

**Comment by alexbegt** [comment]
This is due to code that the Tinkers Construct team removed, It has not been pushed to curse yet. (Commit https://github.com/SlimeKnights/TinkersConstruct/commit/37cf0b2f3b9f90c042302d9518d80328bfcb5610). Turns out on the old version, it would send the BlockState of the Slimy Grass, and Chisel uses that to get the light opacity. (https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/common/block/BlockCarvable.java#L258-L260)
