### ISSUE TITLE
Depreciated blocks between 1.9 and 1.10?

### ISSUE THREAD

**Issue by Vaerys-Dawn** [Chisel-Team/Chisel#193]
so upon updating between minecraft 1.9 and 1.10 there seems to have been some blocks depreciated (or not yet implemented).

affected version
Chisel - MC1.9.4-0.0.6.33

any word on that?

affected blocks:
fantasy/*
fantasy2/*
sandstone/*
there may be others i have not yet noticed

**Comment by Drullkus** [comment]
Between 1.9 and 1.10? We never ported at all because our 1.9 jars work on 1.10. We literally never compiled with version 1.10. You probably were using FTB Unstable or one of the jars from our Jenkins.

Fantasy(2), Grimstone, Holystone, Leaves, Linemarkings, and several others if I forgot were nuked.
- If you're looking for black-themed blocks like Grimstone, check out new Basalt. Coal and Flint blocks are coming in the future.
- If you're looking for white-themed blocks like Holystone or Fantasy, check out the new and retextured Marble blocks. Quartz blocks are coming in the future.
- (Yellow) Sandstone variations got retextured and Red Sandstone Variations were created.

And then there's blocks I still have to retexture (Redstone, Ice, etc). [Glowstone just got finished](https://twitter.com/Drullkus/status/754240839509942272), expect those soon. :P
