### ISSUE TITLE
Weird rendering prioritization

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#233]
Ignore the sexy cape.

The issue is occurring when there's platform of blocks that use the TRANSLUCENT layer. The problem is more visible when seen in F5, but still seen in first-person.

![2016-09-21_16 49 29](https://cloud.githubusercontent.com/assets/5010174/18732888/6be50904-801b-11e6-9b6b-7de1133baf87.png)

**Comment by KnightMiner** [comment]
Pretty sure this is a vanilla issue as I have seen it with slime blocks and ice. Vanilla does not know how to properly order semi-transparent faces due to something with OpenGL rendering (beyond what I understand). I would link you my issue report where TheMogMiner mentioned, but the issue for this on the vanilla bug tracker has split and been merged so much I lost track of where it ended up.

For what you want there, I would suggest to just use CUTOUT and make the water texture inside solid colored, especially for lava since it is not transparent in the end, though adding some additional face culling would definitely help (then the top faces would look odd in a lot less cases)
