### ISSUE TITLE
[1.10.2] iChisel Causes Client Crash

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#247]
When you right click on a iChisel to open the GUI it crashes the client

[Gist Crash Report](https://gist.github.com/Stuart74/bf882409250102ecc64d28c132c3ccc1)

Chisel Version  1.9.4-0.0.6.46
Forge Version 2092

**Comment by Drullkus** [comment]
That is weird. I have been using my iChisel left and right just fine. What were you doing before you crashed?

**Comment by ghost** [comment]
nothing i logged as one of my players reported the issue and as the admin ii wanted to confirm the crash and get a crash report.

I tested to see if it occurred  in single player since we use sponge for forge on our server and wanted to ensure that it was not a sponge related crash which it isn't as it crashes in single player also.

**Comment by tterrag1098** [comment]
I would test without so many other mods installed. The crash here is in vanilla code so I suspect something else is messing with things.

**Comment by robaimes** [comment]
Replicated it here: http://pastebin.com/VNhs7vnZ

I believe the problem is NEI as it is also preventing other GUI aspects from showing while JEI shows. The relevant issue is here: https://github.com/TheCBProject/NotEnoughItems/issues/25

Edit: Removed NEI and the problem goes away, so the above issue should be where further discussion takes place.
