### ISSUE TITLE
Can't get Andesite or Diorite Chisel versions ???

### ISSUE THREAD

**Issue by mcdodge34** [Chisel-Team/Chisel#280]
Not sure what's wrong but if I put Andesite or Diorite in the Chisel, I get the regular Stone variant of the Stone instead, it works fine with Granite which is very strange, any idea what could cause this, I would suspect a mod does this and I'm guessing either Quark or Cyclic for some reasons, any ideas ???

**Comment by ghost** [comment]
To be more specific. Vanilla smooth stone, grannite and andesite can be chiseled into the available smooth stone options options as well as raw and polished granite and adnesite. The andesite, etc. bricks added by quark cannot be chiseled into or out of.
Diorite options (the same for smooth stone, andesite and granite):
![screen shot 2016-11-17 at 4 13 17 pm](https://cloud.githubusercontent.com/assets/15851438/20413268/d8afe5c6-ace0-11e6-814e-a0c3fd25ccd6.png)
I used cheats to swap my diorite for the chiseled versions and they can be swapped around normally (as long as I don't switch to raw or polished).
![screen shot 2016-11-17 at 4 13 29 pm](https://cloud.githubusercontent.com/assets/15851438/20413271/dafa8b92-ace0-11e6-9265-8e1703770ca1.png)
I also mentioned it in the Quark issues (https://github.com/Vazkii/Quark/issues/218) because the Quark bricks cannot be chiseled into or out of. I'm hoping the two are related and can be fixed together.

**Comment by Kalmeira** [comment]
If you have DarkUtils installed, disable a DarkUtils config for making stone ore dict. to fix the problem.

**Comment by ghost** [comment]
According to Darkhax, the ore dict for the stone is just to allow decorative stones to be used in recipes. Shutting it off fixes the chisel problem. Since there's no granite furnace or cobble, I can live without the dict for now.
In the long run, there might have to be special handling for minecraft:stone to enable decorative stone to be used universally or something.

**Comment by KnightMiner** [comment]
Why not simply remove the stone oredict chiseling in favor of a static call to the vanilla block and keep oredict for granite and diortie? Most mods that add something predicted as stone are unlikely to be equivalent, but rather just available for crafting the same. (For example, I add a decorative brown stone for a biome, I would not expect getting vanilla bricks from it)

**Comment by ghost** [comment]
Yep were also getting this issue on our server, disabling parts of another mod always feel a major no no to me, can anyone confirm that it has not had any remifications further on? @charlesbevans mentions the fix will mean "no granite furnace or cobble" granite i can live with but if it kills the ability to make the vanilla furnace then thats a serious issue with the fix

**Comment by ghost** [comment]
Disabling the oredict doesn't break anything. I've had it disabled in the DW20 pack since Kalmeira replied to me with no problems. Given Chisel's popularity, it should probably be off by default.
As far as packs go, it's your game. If it's the DW20 pack you're running, it's sorely lacking in decorative features anyway (Big Doors, Architecture Craft, etc.), go nuts.

**Comment by ghost** [comment]
Yep its my own modpack (though its public hence my caution) so its just the oredict for stone in dark utilities that needs disabling?
also will look up the other mods, always good to have decorative blocks!

**Comment by ghost** [comment]
@mrgreaper ArchitectureCraft is a nice sub for the lack of Carpenter's Blocks in 10.2. Big Doors adds 3x3 doors for all your hammering needs. Also check ExtraBlocks. It lets you chisel into TFC colored stone variants.

**Comment by ghost** [comment]
@charlesbevans cool will look them up as im updating wednesday thanks

**Comment by ghost** [comment]
@mrgreaper Interesting pack. A lot of the same mods I'm using in the dwarf-tech themed pack I'm working on. (Inspired by Embers.) I'm looking up the stream.
We're completely off topic now, so PM me at scribbler957 on Curse if you want to talk more.

**Comment by mcdodge34** [comment]
Ok, sorry to bring this back again after such a long time, but I'm now playing on FTB Beyond pack and this issue is still there, I see people mention to disable DarkUtils Vanilla stone Oredict or something, I have no problems doing this, but I wanna know what will be disabled if I do this, its clearly marked that disabling this VanillaStone Oredict would break many DarkUtils recipes, anyone know which ones are broken before I do the changes and find out a crap ton of recipes of DarkUtils mod don't work anymore...

**Comment by ghost** [comment]
The Final Answer
The oredict in Dark Utilities serves exactly one purpose. It lets you use decorative vanilla stone (andesite, etc.) in place of cobble in crafting recipes. With it on, you can use diorite to make a furnace or andesite to make a stone pick.
**Nothing in Dark Utils will be broken if you disable the oredict option, and you will be able to chisel decorative stone again.**

**Comment by mcdodge34** [comment]
Cool, will do this change and transmit this to the FTB Beyond team, they will probably adjust the config accordingly in their next release.

**Comment by mcdodge34** [comment]
Here I confirm that just by editing the DarkUtils Vanilla stone oredict thingy, it solves the issue, yeah, now I can use the fantastic Andesite bricks, wide bricks in my builds...
