### ISSUE TITLE
Fancy Block Particles missing top face particles

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/Chisel#357]
Fancy Block Particles can't find particles for the top face of Chisel blocks.

**Chisel version:** [0.0.8.11](https://minecraft.curseforge.com/projects/chisel/files/2382238)
**FBP version:** [2.0](https://minecraft.curseforge.com/projects/fancy-block-particles/files/2382206)
**Forge version:** [1.10.2-12.18.3.2221](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2221/forge-1.10.2-12.18.3.2221-changelog.txt)

**Example:** https://streamable.com/deuzl

**Comment by tterrag1098** [comment]
We don't do anything special for top faces....this seems like a bug in that mod.

**Comment by TominoCZ** [comment]
Haven't  tried this yet, but all I can say is that it's not a bug, since it's not a regular block..
I don't know how exactly to explain this to you, but the way my mod gets the top texture is that it gets the texture **file** which the block uses. The Chisel block uses many texture files on one side of the "block".

**Comment by Drullkus** [comment]
Wtf. That's cool!

Isn't it possible to just request the particle texture from the model itself? The texture is same on all 6 faces, I don't get why you're getting a null texture for the topside.

**Comment by TominoCZ** [comment]
Oh wait.. I forgot to look at the gif :D I thought that this mod allows you to carve blocks...
Well.. with getting the top texture.. its kind of a shot in the dark... you get a list of "BakedQuads" and you never know which one is the top one... so i basically select the first one.. I know how to fix it so that it has a texture, but it might not be the top texture..

**Comment by TominoCZ** [comment]
The texture isn't null tho..
