### ISSUE TITLE
Tesselating block error 

### ISSUE THREAD

**Issue by balla2185** [Chisel-Team/Chisel#627]
have gotten this same error 5 times now, first 4 were marble this one seems to be basalt,

from what mods have stated they are trying to receive power when touching AE2

**Comment by tterrag1098** [comment]
Log? Version? Anything?

**Comment by Gyromax** [comment]
Hope it's ok, if i use an Invalid Post, because i have the same Error. May be able to provide a few more information though.

Judging from what i understand of the Log, it's a Laboratory Block that's having the Tessalating Block Error.

I'm using the following Versions:
Minecraft: 1.12.2
CTM: 0.2.3.12
Chisel: 0.2.0.31
Forge: 14.23.2.2654
Optifine: HD_U_D1

The Error comes with and without Optifine. Also i disabled Tessalating in my AMD-Settings and tried with that.
I'm using the Technic-Launcher to provide the Modpack to my Sister, but the Crash also shows with the normal MC-Launcher.

Would be great to get at short notice at least a Work Around or Information on how i can fix it, because at least for now, i can't even join the Game.

And here the Pastebin of the latest-Crashlog. If needed i can provide more.
https://pastebin.com/ADXGycLR

If you need more Information, just tell me and i'll try to gather them as fast as possible.

Thanks for your time!

Edit: Removed some Writing and Spelling Mistakes.

**Comment by Gyromax** [comment]
Here another Crash-Report from this morning.
https://pastebin.com/3xmL7pJB
i replaced all Laboratory 4-Blocks with Stone, now the Error shifted to Marble 7.
I used the Vanilla command " /fill x1 y1 z1 x2 y2 z2 minecraft:stone 0 replace chisel:laboratory 4 "

I also deleted Chisel from the Server which had a kinda interesting effect. I started my Server once, let "FML" delete all Chisel-Blocks, then shut the Server down, moved Chisel back to it and get it running again.
Most of the Chiseled-Blocks were gone, but about 50% at least in my Place have stayed. I could Login onto the Server then, but well my base was a real mess, so i rebooted a Backup i've done before removing Chisel.

**Comment by tterrag1098** [comment]
This was a bug in recent versions of Thermal Dynamics where they used an unreleased version of the CTM API. It has since been fixed.

Reference: 
https://github.com/CoFH/Feedback/issues/1010
https://github.com/CoFH/ThermalDynamics/commit/d65a2a7e20dcd90518d9e217a71b2da47c7ab495
