### ISSUE TITLE
Update the Ender Offset Wand.

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#666]
Right now the Ender Offset Wand is not particularly useful. It can only offset certain blocks with connected textures. It would be great if it could offset textures on ANY Chiselled block. Rotating textures would also be a great addition.

**Comment by ZombieHDGaming** [comment]
2 things, 1. The Ender Offset Wand is kinda useless for 95% of the textures since they are all the same when put together. The select few textures it supports are for good reason since the texture takes up multiple blocks in order for it to be a "full" texture, so it would make sense for the wand to be useful with them. All textures, however, not so much. And 2. The rotating texture could be a better feature to have, but it would probably be better to have another tool for that. But that's just my two sense. tterrag might have more to say, but I feel that's probably the gist of what he might say.

**Comment by ghost** [comment]
Sorry, I guess I wasn't clear enough in my previous post. I want to be able to offset textures by non-integer amounts. Ie, by bits, not blocks. In that case, any block that is not a simple repeating texture can be usefully transformed. In particular, any block with a border would be useful to transform that way, when used with Chisels and Bits. Below I have a picture of a decorative wall with windows that I threw together as an example. If I try to chop-up regular glass or futura blocks on non-block boundaries the textures don't work. If I could offset the textures before chopping the blocks (and have that carry over to the chisels and bits pieces) then I could solve these visual issues. 

As an aside, I should point out that Chisels doesn't provide a borderless version of the normal glass block. Flat Colored Blocks provides a huge number of tinted borderless glasses, but none that are colorless. 

![wall](https://user-images.githubusercontent.com/154508/38038313-b0d89006-3278-11e8-850d-28f653a2a636.png)

**Comment by tterrag1098** [comment]
Setting aside the complexities of such a system, the offset wand does not currently (and has no way to) affect Chisels&Bits blocks.
