### ISSUE TITLE
Updating from 1.10.2 to 1.12.2 will remove many chisel blocks in world.

### ISSUE THREAD

**Issue by TheTechBandit** [Chisel-Team/Chisel#683]
I'm managing a 1.10.2 modded server and we're trying to update to 1.12.2. We were using Chisel-MC1.10.2-0.0.13.29 and are updating to Chisel-MC1.12.2-0.2.0.31. However, when we updated, specific chisel blocks were removed from the world. The most important of these is the marble block. In 1.10.2 it seems some of the chiseled marble blocks had the ID of marbleextra... However in 1.12.2 the ID seems to have changed to marble2. Since marbleextra no longer exists, all the old marbleextra blocks are removed upon loading the world. Is this an intentional change, or a mistake? Is there any way to update without removing all the blocks with changed IDs? If more information such as logs or a modlist is needed I can provide those.

**Comment by tterrag1098** [comment]
During the change from 1.10 to 1.12, mojang enforced a new restriction on block names, that they must all be lowercase. Since this would already surely break most mods, and some of our own blocks, we took the opportunity to clean up some of our IDs. At this time the only way to manage the migration would be a tool to remap IDs (does Midas Gold still exist)?)

**Comment by KnightMiner** [comment]
Forge has a tool to remap IDs using the missing mapping event

**Comment by TheTechBandit** [comment]
Midas Gold was last updated in May 2013 and no longer works. Where can I find that forge tool or what is it called?

**Comment by tterrag1098** [comment]
It's not a user-side tool. It's something we could potentially add as a mod, but imo it would not be worthwhile since you are very likely to run into many other mods that break IDs between 1.10/1.12.
