### ISSUE TITLE
Multiblock Offset is being reset after restarting the game (Server)

### ISSUE THREAD

**Issue by jano1221** [Chisel-Team/Chisel#756]
**Issue:**  Offset of multiblock setted on server is being reset after restarting the game.

**Steps to reproduce:**
- Join a server
- Set an offest of the big fan(3x3) with Ender Offset Wand:
![2018-12-09_23 46 46](https://user-images.githubusercontent.com/26485647/49703995-1e6c7980-fc0d-11e8-8a92-b900a962b591.png)
- Restart the game
- Join the server again
- 🤔:
![2018-12-09_23 48 56](https://user-images.githubusercontent.com/26485647/49703999-275d4b00-fc0d-11e8-9475-489d758f2451.png)

_(Server is not being restarted)_

Minecraft version 1.12.2
Chisel version 0.2.1.35 (Latest)
Server Forge version 14.23.5.2772

**Comment by tterrag1098** [comment]
This is a tricky one. I think it only occurs when the blocks are in chunks that remain loaded when the player is offline. Since I only send the data on (server-side) chunk load, it won't be resent ever to that client. Restarting is only significant because it clears the client's caches. I probably need to implement an initial join packet sent to the player that contains all offset data.

**Comment by vrelk** [comment]
What release was this fix included in? This seems to be occurring in 1.0.1.44 (mc1.12.2), which was released after this fix was committed.

**Comment by tterrag1098** [comment]
If you are having an issue with this feature, please report it in a new issue.
