### ISSUE TITLE
ProjectRed blocks

### ISSUE THREAD

**Issue by xJon** [Chisel-Team/Chisel#781]
Using the latest version of Chisel, I can turn ProjectRed blocks to other ones from the same mod.
For example, I can chisel a marble block into a block of sapphire, which's pretty cool.

**Screenshot**
![Screenshot_2](https://user-images.githubusercontent.com/8945347/61184020-eee28b80-a68b-11e9-937f-720bc02b8079.png)

(Already reported to ProjectRed at https://github.com/MrTJP/ProjectRed/issues/1495)

**Comment by MrTJP** [comment]
If a Chisel dev can give some insight on how Chisel determines blocks are just decorative versions of each other, I can fix this asap. Project Red currently uses a single block for all of its decorative/storage blocks, but they obviously are not equal and cannot be converted like that.

**Comment by tterrag1098** [comment]
We provide an IMC API for other mods to register their blocks to chisel. See 
https://github.com/Chisel-Team/Chisel/blob/1.12/dev/src/main/java/team/chisel/api/IMC.java

**Comment by MrTJP** [comment]
Thanks. If you have a stable maven I can build off of, I can use API directly. Otherwise, I'll just copy the strings from the IMC class.

**Comment by tterrag1098** [comment]
Better to copy strings (javadoc recommends this), but if you prefer references API jars are available at https://maven.tterrag.com/team/chisel/Chisel/

**Comment by xJon** [comment]
I want to confirm I happened to try to reproduce this on FTB Ultimate Reloaded, which has both Chisel and ProjectRed installed, and could not.
So I'm not exactly sure what's going on, unless FTB fixed it on their own end.

**Comment by MrTJP** [comment]
Just wanted to make sure this is the right way to fix this, since this is a pretty major exploit. First I removed all blocks by using the Remove Variation message. Then I added marble and basalt to their respective groups. It seems to have fixed it, but asking in case there are still other ways to make this conversion (not familiar with Chisel).

MrTJP/ProjectRed#1503

**Comment by tterrag1098** [comment]
Wait, you're trying to *remove* your blocks from chisel? Why are they there in the first place? We don't have any integration with Project Red, and the group doesn't use oredict.

**Comment by MrTJP** [comment]
Oh really? I thought that maybe Chisel was auto registering, because I sure as hell don’t have any chisel integration. Maybe op has added them incorrectly through configs if that is possible? 

Edit: actually, I am able to reproduce the bug. The blocks are indeed auto-registered with no additional configuration required.

**Comment by tterrag1098** [comment]
Not sure what it could be. Sure you don't have some old integration somewhere that was forgotten about? We simply don't have any compatibility for marble. Quark has to register its marble, for example.

**Comment by MrTJP** [comment]
You’re right actually, found the issue. This is an old PR plugin that was suppose to be dormant. This can be closed here, will fix on my end. Apologies :)
