### ISSUE TITLE
[1.12] Yellow (and only yellow) chiseled glass causes crash on break 

### ISSUE THREAD

**Issue by jraynolds** [Chisel-Team/Chisel#816]
I'm using Chisel (1.12.2-1.0.1.44) and chiselsandbits (14.33) and I've discovered destroying yellow chiseled glass, no matter the type (panel, brick, etc) causes a crash. The head of the error message is this:

`java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block atlcraft:atlcraft_lamppost01_edge_acacia_middle, it is not an allowed value` 

It seems clear to me this is an issue between ATL Craft Candles (1.9) and Chisel. Why it's only happening on yellow block breaking, however, is much more mysterious.

A full log is [here](https://paste.minecrafthelp.co.uk/?1a5874298829c5ef#99gv9GWtWRafCaSfLvdxTzubaLEag2yBLb5MkH5r2rew).

**Comment by tterrag1098** [comment]
Something has corrupted your clientside ID table, the problem is that it's trying to spawn a particle for the wrong block because particles are spawned by ID.

Here's the line causing the crash https://github.com/Chisel-Team/Chisel/blob/1.12/dev/src/main/java/team/chisel/client/util/ClientUtil.java#L92

I don't think this is chisel or atlcraft's fault, but probably something like JEID, which is not something I support as it's known to cause world breaking issues.

**Comment by jraynolds** [comment]
Thank you for your help! Indeed it was JEID. I've rolled back to a previous version while I search for an appropriate replacement. Do you happen to know of any?

**Comment by tterrag1098** [comment]
All of the ID extender mods are fundamentally flawed, I wouldn't recommend any of them. If you happen to find one that works, great, but it's at your own risk.
