### ISSUE TITLE
Mod is illegal to distribute in modpacks

### ISSUE THREAD

**Issue by immibis** [Chisel-Team/Chisel#846]
Hi,
This mod is distributed under the GPL license, with no Minecraft exception. ~~That means it's illegal to distribute any modpack containing Chisel.~~ Is this intentional?

Apologies if this is a duplicate. I searched the issue tracker and didn't find one.

**Edit:** On second thought, it might be legal to distribute the entire modpack under GPL, since the modpack doesn't actually include a copy of Minecraft. However, it's illegal if there are any closed source mods in the modpack.

**Comment by tterrag1098** [comment]
I can't find an interpretation of the clause

> You may copy and distribute verbatim copies of the Program's
source code as you receive it, in any medium, provided that you
conspicuously and appropriately publish on each copy an appropriate
copyright notice and disclaimer of warranty; keep intact all the
notices that refer to this License and to the absence of any warranty;
and give any other recipients of the Program a copy of this License
along with the Program.

that leads to this conclusion. Modpacks are not building software that is linking this code, they are distributing it as part of a collection. The jar still stands alone, and contains the license file within it.

Regardless, this is the license the mod has, it's virtually impossible to change at this point, so I'm not sure what the point of this issue is. CurseForge TOS overrides the license anyhow when it comes to inclusion in modpacks.

**Comment by immibis** [comment]
That's because it would be this clause instead:

> You must cause any work that you distribute or publish, that in
> whole or in part contains or is derived from the Program or any
> part thereof, to be licensed as a whole at no charge to all third
> parties under the terms of this License.

The "mere aggregation" clause could be interpreted to allow modpacks, as long as those modpacks do not have customizations for Chisel, which would be an unusual situation.

Granted, nobody has ever tested it, and Minecraft mod licensing mostly runs on trust and shame, not on the legal system.
